### ISSUE TITLE
Set unused objects to have EditorOnly tag instead of removing.

### ISSUE THREAD

**Issue by MistressPlague** [euan142/LazyOptimiser#13]
This means unpacked prefab avatars wont near-irreversibly lose meshes or objects, they simply just wont be uploaded to VRC.

**Comment by euan142** [comment]
The optimiser doesn't alter the avatar in the scene but rather a prefab which is created by the sdk during build meaning nothing should be lost. Marking a gameobject EditorOnly by default in unity does nothing, it's actually removed as part of a build callback in the sdk which is the exact same way objects are removed in the optimiser
